//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Manager
    {
        public int Id_Branch_Manager { get; set; }
        public int IdBranch { get; set; }
        public int IdEmployee { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RestaurantBranch RestaurantBranch { get; set; }
    }
}
