//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatBanOnlineEntities : DbContext
    {
        public DatBanOnlineEntities()
            : base("name=DatBanOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch_Manager> Branch_Manager { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Image_Menu> Image_Menu { get; set; }
        public virtual DbSet<Image_TableType> Image_TableType { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Order_Menu> Order_Menu { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RestaurantBranch> RestaurantBranches { get; set; }
        public virtual DbSet<RestaurantTable> RestaurantTables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_Type> Table_Type { get; set; }
    
        public virtual int Delete_RestaurantBranch(Nullable<int> idBranch)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_RestaurantBranch", idBranchParameter);
        }
    
        public virtual ObjectResult<Get_List_RestaurantBranch_All_Result> Get_List_RestaurantBranch_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_RestaurantBranch_All_Result>("Get_List_RestaurantBranch_All");
        }
    
        public virtual ObjectResult<Get_RestaurantBranch_By_Id_Result> Get_RestaurantBranch_By_Id(Nullable<int> idBranch)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_RestaurantBranch_By_Id_Result>("Get_RestaurantBranch_By_Id", idBranchParameter);
        }
    
        public virtual int Insert_RestaurantBranch(string address, string description)
        {
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_RestaurantBranch", addressParameter, descriptionParameter);
        }
    
        public virtual int Update_RestaurantBranch(Nullable<int> idBranch, string address, string description)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_RestaurantBranch", idBranchParameter, addressParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Get_List_Table_By_Restaurant_Id_Result> Get_List_Table_By_Restaurant_Id(Nullable<int> restaurantId)
        {
            var restaurantIdParameter = restaurantId.HasValue ?
                new ObjectParameter("RestaurantId", restaurantId) :
                new ObjectParameter("RestaurantId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Table_By_Restaurant_Id_Result>("Get_List_Table_By_Restaurant_Id", restaurantIdParameter);
        }
    
        public virtual ObjectResult<Get_List_Table_Available_Result> Get_List_Table_Available(Nullable<int> restaurantId, Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime)
        {
            var restaurantIdParameter = restaurantId.HasValue ?
                new ObjectParameter("RestaurantId", restaurantId) :
                new ObjectParameter("RestaurantId", typeof(int));
    
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Table_Available_Result>("Get_List_Table_Available", restaurantIdParameter, beginTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<Get_List_TableType_Result> Get_List_TableType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_TableType_Result>("Get_List_TableType");
        }
    
        public virtual ObjectResult<Get_Customer_By_Login_Result> Get_Customer_By_Login(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Customer_By_Login_Result>("Get_Customer_By_Login", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Get_Employee_By_Login_Result> Get_Employee_By_Login(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Employee_By_Login_Result>("Get_Employee_By_Login", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Insert_Customer_Result> Insert_Customer(string cMND, string fullName, string phone, string address, string password)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Insert_Customer_Result>("Insert_Customer", cMNDParameter, fullNameParameter, phoneParameter, addressParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Insert_Order_Result> Insert_Order(Nullable<int> idCustomer, Nullable<int> numberOfTable, Nullable<int> numberOfCustomer, Nullable<int> idBranch, Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime, Nullable<int> orderStatus, string description)
        {
            var idCustomerParameter = idCustomer.HasValue ?
                new ObjectParameter("IdCustomer", idCustomer) :
                new ObjectParameter("IdCustomer", typeof(int));
    
            var numberOfTableParameter = numberOfTable.HasValue ?
                new ObjectParameter("NumberOfTable", numberOfTable) :
                new ObjectParameter("NumberOfTable", typeof(int));
    
            var numberOfCustomerParameter = numberOfCustomer.HasValue ?
                new ObjectParameter("NumberOfCustomer", numberOfCustomer) :
                new ObjectParameter("NumberOfCustomer", typeof(int));
    
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Insert_Order_Result>("Insert_Order", idCustomerParameter, numberOfTableParameter, numberOfCustomerParameter, idBranchParameter, beginTimeParameter, endTimeParameter, orderStatusParameter, descriptionParameter);
        }
    
        public virtual int Insert_Order_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Order_Table");
        }
    
        public virtual ObjectResult<Get_List_Order_Table_Result> Get_List_Order_Table(Nullable<int> idOrder)
        {
            var idOrderParameter = idOrder.HasValue ?
                new ObjectParameter("IdOrder", idOrder) :
                new ObjectParameter("IdOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Order_Table_Result>("Get_List_Order_Table", idOrderParameter);
        }
    
        public virtual ObjectResult<Get_Order_Result> Get_Order(Nullable<int> idOrder)
        {
            var idOrderParameter = idOrder.HasValue ?
                new ObjectParameter("IdOrder", idOrder) :
                new ObjectParameter("IdOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Order_Result>("Get_Order", idOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Employee_Permission_By_Id(Nullable<int> idEmployee)
        {
            var idEmployeeParameter = idEmployee.HasValue ?
                new ObjectParameter("IdEmployee", idEmployee) :
                new ObjectParameter("IdEmployee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Employee_Permission_By_Id", idEmployeeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Employee_Roles_By_Id(Nullable<int> idEmployee)
        {
            var idEmployeeParameter = idEmployee.HasValue ?
                new ObjectParameter("IdEmployee", idEmployee) :
                new ObjectParameter("IdEmployee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Employee_Roles_By_Id", idEmployeeParameter);
        }
    
        public virtual ObjectResult<Get_All_Table_Result> Get_All_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Table_Result>("Get_All_Table");
        }
    
        public virtual ObjectResult<Get_List_Order_All_Result> Get_List_Order_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Order_All_Result>("Get_List_Order_All");
        }
    
        public virtual ObjectResult<Get_List_Order_By_Status_Result> Get_List_Order_By_Status(Nullable<int> orderStatus)
        {
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Order_By_Status_Result>("Get_List_Order_By_Status", orderStatusParameter);
        }
    
        public virtual ObjectResult<Get_Customer_By_Id_Result> Get_Customer_By_Id(Nullable<int> idCustomer)
        {
            var idCustomerParameter = idCustomer.HasValue ?
                new ObjectParameter("IdCustomer", idCustomer) :
                new ObjectParameter("IdCustomer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Customer_By_Id_Result>("Get_Customer_By_Id", idCustomerParameter);
        }
    }
}
