//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatBanOnlineEntities : DbContext
    {
        public DatBanOnlineEntities()
            : base("name=DatBanOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch_Manager> Branch_Manager { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Image_Menu> Image_Menu { get; set; }
        public virtual DbSet<Image_TableType> Image_TableType { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Order_Menu> Order_Menu { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RestaurantBranch> RestaurantBranches { get; set; }
        public virtual DbSet<RestaurantTable> RestaurantTables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_Type> Table_Type { get; set; }
    
        public virtual int Delete_RestaurantBranch(Nullable<int> idBranch)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_RestaurantBranch", idBranchParameter);
        }
    
        public virtual ObjectResult<Get_List_RestaurantBranch_All_Result> Get_List_RestaurantBranch_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_RestaurantBranch_All_Result>("Get_List_RestaurantBranch_All");
        }
    
        public virtual ObjectResult<Get_RestaurantBranch_By_Id_Result> Get_RestaurantBranch_By_Id(Nullable<int> idBranch)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_RestaurantBranch_By_Id_Result>("Get_RestaurantBranch_By_Id", idBranchParameter);
        }
    
        public virtual int Insert_RestaurantBranch(string address, string description)
        {
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_RestaurantBranch", addressParameter, descriptionParameter);
        }
    
        public virtual int Update_RestaurantBranch(Nullable<int> idBranch, string address, string description)
        {
            var idBranchParameter = idBranch.HasValue ?
                new ObjectParameter("IdBranch", idBranch) :
                new ObjectParameter("IdBranch", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_RestaurantBranch", idBranchParameter, addressParameter, descriptionParameter);
        }
    }
}
