//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id_Deposit { get; set; }
        public int IdOrder { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
