//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_TableType
    {
        public int Id_Image_Table_Type { get; set; }
        public Nullable<int> Id_Table_Type { get; set; }
        public string Url { get; set; }
    
        public virtual Table_Type Table_Type { get; set; }
    }
}
