//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantTable()
        {
            this.Order_Table = new HashSet<Order_Table>();
        }
    
        public int IdTable { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<int> IdTableType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Deactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Table> Order_Table { get; set; }
        public virtual RestaurantBranch RestaurantBranch { get; set; }
        public virtual Table_Type Table_Type { get; set; }
    }
}
